name: Metrics
on:
  # Schedule daily updates
  # Run on AM 5:00 in Republic of Korea
  schedule: 
    - cron: '0 20 * * *'
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest    
        with:
          token: ${{ secrets.METRICS_TOKEN }} 
