# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 20 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-dkswnkk-main.svg
          # Options
          user: dkswnkk
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-dkswnkk-sub.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: Update github-metrics
        run: |
          git config user.name dkswnkk
          git config user.email dkswnkk.dev@gmail.com
          git add -A .
          git commit -m "Update github-metrics-dkswnkk.svg"
          git push
